<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5OULTSJ" failures="1" tests="4" name="Default test(failed)" time="0.114" errors="0" timestamp="13 Jun 2022 02:32:04 GMT">
  <testcase classname="Factory.Test2" name="testFail" time="0.025">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="Factory.Test2" name="testFail" time="0.002">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="Factory.Test2" name="testFail" time="0.004">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="Factory.Test2" name="testFail" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Factory.Test2.testFail(Test2.java:24)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="Factory.Test2" name="test22mehtod" time="0.0">
    <ignored/>
  </testcase> <!-- test22mehtod -->
  <testcase classname="Factory.Test2" name="test2method" time="0.0">
    <ignored/>
  </testcase> <!-- test2method -->
</testsuite> <!-- Default test(failed) -->
